spreadsheetClientID = "721896546129-45fubg5ij5m84qoikbnqgu73u1bhvh4f.apps.googleusercontent.com"
spreadsheetClientSecret = "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"
spreadsheetRefreshToken = "1//04su8tUCzoEvoCgYIARAAGAQSNwF-L9IrqC9NbLeo1xRlVG3PCKNATdZ5Th6TbPJQiyWUwsj5kq_SEYlAvZWlcXN-muvtfy7vAFE"
spreadsheetID = "1OcrfWGQvAQkidv2nu9ZYG9RTPpygpIQb9KM9acbD-GY"
