name: Daily Full Build Pipeline (2201.3.x)
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
# on:
#   workflow_dispatch:
#   schedule:
#     - cron: '30 18 * * *'   # 00:00 in LK time (GMT+5:30)


jobs:
  nballerina-build:
    # needs: build-distribution
    name: Build nBallerina
    # runs-on: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ballerina-platform/setup-ballerina@v1
        name: Install Ballerina
        with:
          version: 2201.7.4
      - run: bal version
      - run: bal run dashboard-extractor.bal

    # steps:
    #   - name: Checkout Repository
    #     uses: actions/checkout@v2
    #   - name: Set up JDK 11
    #     uses: actions/setup-java@v2
    #     with:
    #       distribution: 'adopt'
    #       java-version: '11'
    #   - name: Install Python Packages
    #     run: |
    #       pip install requests
    #       pip install retry
    #       pip install PyGithub
    #       pip install cryptography
    #       pip install httplib2
    #   - name: Clone nBallerina repository
    #     run: git clone https://github.com/ballerina-platform/nballerina.git
    #   - name: Switch to last working nBallerina commit
    #     run: git checkout jballerina-2201.3
    #     working-directory: nballerina
    #   - name: Download Linux Deb Installer
    #     uses: actions/download-artifact@v2
    #     with:
    #       name: Linux Installer deb
    #   - name: Install Ballerina DEB
    #     run: sudo dpkg -i ballerina-*-linux-x64.deb
    #   - name: Run compiler tests
    #     working-directory: nballerina/compiler
    #     run: bal test --disable-groups private
      
 